function settingsTable  = getZEALSettingsTable()
%% function to set up table with input documentatino to ZEAL

% 'parameter'       :       type      :         default     (expected values)      :                 description
% ZC
% 'Order'                     integer                   20            (>0)                              The maximum expansion order of ZC moments
% 'ChiCoeffPath'          char                [pwd '/chi_coefficients/']                     Path to folder with pre-computed chi coefficients for order N with name chiCoeffs_order_N
% SHAPE
% 'GridRes'                 integer                   64            (>=32)                          The side length of the cubic grid
% 'Shape'                      char                    'MS'          ('MS', 'SAS', 'vdw', 'electron_density')     The molecular shape function (surfaces/densitites)
% 'ProbeRadius'          integer                  1.4            (>=0)                           The radius of the probe in Å used for the surface computations
% 'SmearFactor'          double                    0.3           (>0, <1)                       Fraction of grid to smear out atoms over when generating electron density
% 'ShellThickness'        integer                   2            (>0)                              Thickness of surfaces (shells) in grid units
% SEARCH
% 'FunEvals'                integer                 300            (>0)                             Number of ZEAL score evaluations until search stops
% 'AlignLater'                logical                 false         (true/false)                   If false then ZEAL will not automatically align upon object construction.
%                                                                                                                  Manually start using  shapeAlign(ZEALobject)
% STRUCTURES
% 'fix_includeHetatoms'     logical             false             (true/false)             Flag to indicate if HETATM records should be included in fixed structure
% 'rot_includeHetatoms'                                                                               "---" in rotating structure
% fix_includeHatoms'     logical                 false             (true/false)             Flag to indicate if Hydrogen atoms should be included (if exists) in fixed structure
% rot_includeHatoms'                                                                                   "---" in rotating structure
% 'fix_chainID'                 char                     'A'          ('all' or 1-letter char)    The chain ID that should be selected ('all' = all chains) in fixed structure
% 'rot_chainID'                                                                                              "---" in rotating structure
% 'fix_altLocID'                char                     'A'        ('all' or 1-letter char)      The ID of any atom altlocs that should be selected in fixed structure
% 'rot_altLocID'                                                                                              "---" in rotating structure
% 'fix_modelNumber'     integer                  1                                                 The model number that should be selected in the fixed structure
% 'rot_modelNumber'                                                                                     "---" in rotating structure
% MISC
% 'LogLevel'                    char            'standard'     ('none', 'basic', 'standard', 'detailed')     Determines the level of information printed to console

%%

parameterName = {'Order', ...
    'ChiCoeffPath', ...
    'GridRes', ...
    'Shape', ...
    'ProbeRadius', ...
    'SmearFactor', ...
    'ShellThickness', ...
    'FunEvals', ...
    'AlignLater', ...
    'fix_includeHetatoms', ...
    'rot_includeHetatoms', ...
    'fix_includeHatoms', ...
    'rot_includeHatoms', ...
    'fix_chainID', ...
    'rot_chainID', ...
    'fix_altLocID', ...
    'rot_altLocID', ...
    'fix_modelNumber', ...
    'rot_modelNumber', ...
    'LogLevel', ...
    };

MatlabType = {'integer', ...
    'char', ...
    'integer', ...
    'char', ...
    'double', ...
    'double', ...
    'integer', ...
    'integer', ...
    'logical', ...
    'logical', ...
    'logical', ...
    'logical', ...
    'logical', ...
    'char', ...
    'char', ...
    'char', ...
    'char', ...
    'integer', ...
    'integer', ...
    'char', ...
    };

defaultValue = {20, ...
    '[pwd ''/chi_coefficients'']', ...
    64, ...
    'MS', ...
    1.4, ...
    0.3, ...
    2, ...
    300, ...
    false, ...
    false, ...
    false, ...
    false, ...
    false, ...
    'A', ...
    'A', ...
    'A', ...
    'A', ...
    1, ...
    1, ...
    'standard', ...
    };


expectedValue = {'>0', ...
    'folder path', ...
    '>0', ...
    '''MS''/ ''SAS''/ ''vdw''/ ''electron_density''', ...
    '>=0', ...
    '>0, <1', ...
    '>0', ...
    '>0', ...
    'true/false', ...
    'true/false', ...
    'true/false', ...
    'true/false', ...
    'true/false', ...
    '''all'' or 1 letter', ...
    '''all'' or 1 letter', ...
    '''all'' or 1 letter', ...
    '''all'' or 1 letter', ...
    '', ...
    '', ...
    '''none''/ ''basic''/ ''standard''/ ''detailed'' ', ...
    };

description = {'The maximum expansion order of ZC moments.', ...
    'Path to folder with pre-computed chi coefficients for order N with name chiCoeffs_order_N.mat. Use ZC.computeChiCoeffs to compute them.', ...
    'The side length of the cubic grid.', ...
    'The type of molecular shape function.', ...
    'The radius of the probe in Å used for the surface computations.', ...
    'Fraction of grid to smear out atoms over when generating electron density', ...
    'Thickness of surfaces (shells) in grid units.', ...
    'Number of ZEAL score evaluations until search stops', ...
    'If false then ZEAL will not automatically align upon object construction. Manually start alignment using shapeAlign(ZEALobject)', ...
    'Flag to indicate if HETATM records should be included in fixed structure', ...
    '"---" in rotating structure', ...
    'Flag to indicate if Hydrogen atoms should be included (if exists) in fixed structure', ...
    '"---" in rotating structure', ...
    'The chain ID that should be selected (''all'' = all chains) in fixed structure', ...
    '"---" in rotating structure', ...
    'The ID of any atom altlocs that should be selected in fixed structure. Use ''all'' to include all altlocs.', ...
    '"---" in rotating structure', ...
    'The model number that should be selected in the fixed structure', ...
    '"---" in rotating structure', ...
    'Determines the level of information printed to console. ''detailed'' not recommended unless ''AlignLater'' option is enabled.', ...
    };

settingsTable = table(parameterName', MatlabType', defaultValue', expectedValue', description');
settingsTable.Properties.VariableNames = {'parameter','type','default value','expected values','description'};


end






